version: '3'
services:
  app:
    build: .
    volumes:
      - .:/scrappers
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://local_root:local_root_password@mongodb:27017/database_name

  mongodb:
    image: mongo:6.0.4
    volumes:
      - ./.db/mongo:/data/.db
    environment:
      MONGO_INITDB_ROOT_USERNAME: local_root
      MONGO_INITDB_ROOT_PASSWORD: local_root_password
      MONGO_INITDB_DATABASE: database_name
      MONGO_NON_ROOT_USERNAME: local_non_root
      MONGO_NON_ROOT_PASSWORD: local_non_root_password
    ports:
      - "27017:27017"