version: '3'
services:
  app:
    build: .
    command: yarn dev
    volumes:
      - .:/scrappers
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://local_root:local_root_password@database/database_name
    ports:
      - '3000:3000'

  database:
    image: postgres:15.2-alpine
    volumes:
      - ./.db/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: local_root
      POSTGRES_PASSWORD: local_root_password
      POSTGRES_DB: database_name
    ports:
      - '4321:5432'
