import Head from 'next/head'
import React, {useState} from 'react'
import {MenuItem, Select, TextField, Typography} from '@mui/material'
import styled from '@emotion/styled'
import {Registries} from '@/registries'

const Main = styled.main`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding-bottom: 10vh;
  height: 100vh;
  width: 100vw;
  
  > *:not(:first-of-type) {
    margin-top: 1rem !important;
  }
`

const registries = Registries.getAll()

export default function Home() {
  const [registryId, setRegistryId] = useState(registries[0].id)
  const registry = Registries.getById(registryId)
  const [type, setType] = useState(registry?.requisitionTypes[0].value)
  return (
    <>
      <Head>
        <title>Scrappers</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Main>
        <Typography component="div">Notificações de cartórios</Typography>
        <Select
          labelId="registry"
          value={registryId}
          label="Cartório"
          onChange={(e) => setRegistryId(+e.target.value)}
        >
          {registries.map(({id, name}) => (
            <MenuItem key={id} value={id}>{name}</MenuItem>
          ))}
        </Select>
        {registry && (
          <>
            <Select
              labelId="requisition-type"
              value={type}
              label="Tipo de Solicitacao"
              onChange={(e) => setType(+e.target.value)}
            >
              {registry.requisitionTypes.map(({title, value}) => (
                <MenuItem key={value} value={value}>{title}</MenuItem>
              ))}
            </Select>
            <TextField label="Número da solicitação" variant="outlined"/>
            <TextField label="Senha" variant="outlined"/>
          </>
        )}
      </Main>
    </>
  )
}
